### ISSUE TITLE
Add support for DWARF type import

### ISSUE THREAD

**Issue by cmorin6** [nneonneo/ghidra-wasm-plugin#1]
Webassembly supports embedding of DWARF debug information ([documentation](https://yurydelendik.github.io/webassembly-dwarf/)) and most compiler toolchain (rust, emscripten) already support this.

DWARF section are stored as WASM custom section with the corresponding DWARF section name.

Ghidra provides a `DWARFAnalyzer` that can be reused with very little effort to extract DataTypes and function signatures.
There are specificities in the way Wasm function offset and variable location are described in DWARF that would require changes deep in the current ghidra DWARF parsing to make the "Function import"functionality  work so they will be listed in a separate issue.

All that is required to enable DWARF parsing is:
* provide a subclass of `DWARFAnalyzer` that override `canAnalyse()` to support Webassembly.
* define a `DWARFSectionProvider` to provide access to DWARF section content from their name.

I can see two ways this could be implemented with the current code base:

**Option 1**
Create new memory blocks for each custom wasm section using the custom section name as block name and strip the wasm section header.
 
PROS:
* This would match the default behavior for ELF file so the default BaseSectionProvider could be used and the custom `DWARFAnalyzer` would be simple ([example](https://github.com/cmorin6/ghidra-wasm-plugin/blob/master/src/main/java/wasm/analysis/dwarf/WasmDWARFAnalyzer.java))

CONS:
* custom sections content would be duplicated

**Option 2**
Create a custom `DWARFSectionProvider` that map DWARF section to the corresponding wasm custom section.

PROS:
* No changes to the current WasmLoader
* Since we need to duplicate the code of the DWARFAnalyzer to use our custom DWARFSectionProvider, we can remove the "import functions" options that can't be supported easily at the moment but is set to true by default. This would avoid the error message upon analysis if the "import functions" is left to to true.

CONS:
* Duplication of the code of DWARFAnalyzer (~250 line) to use our custom DWARFSectionProvider. Since most of the fields of DWARFAnalyzer are private we would need to duplicate most of the code which would be ugly and harder to maintain.
* the custom `DWARFSectionProvider` would need access to a `WasmModule` instance (probably from `WasmAnalysis`) to map wasm section to DWARF ones. The `DWARFAnalyzer` checks for the presence of sections in it's `canAnalyze()`. This would mean that the `WasmAnalysis` and `WasmModule` would need to be initialized, parsing the module structure, just to know if the `DWARFAnalyzer` should be enabled.

I can make a merge request for this if needed.

**Comment by nneonneo** [comment]
Duplicating content is not such a big issue. They should go into OTHER address space anyway so they won’t affect the loaded memory blocks. Therefore, to avoid code duplication (and maintenance burden), I would go with Option 1. If you want to make a PR, go for it - that would be awesome!

**Comment by nneonneo** [comment]
Also: I don’t have any samples that have any DWARF information, so if you do submit a PR it’d be helpful to include some DWARF-enabled Wasm samples for testing purposes.

**Comment by cmorin6** [comment]
Ok perfect. I'll start working on this and find a sample to share with the merge request.
