### ISSUE TITLE
Cannot invoke "ghidra.program.model.mem.MemoryBlock.getStart()"

### ISSUE THREAD

**Issue by seltix5** [nneonneo/ghidra-wasm-plugin#11]
Hello,
I'm running :
ghidra_10.1.2_PUBLIC_20220125
ghidra_10.1.2_PUBLIC_20220312_ghidra-wasm-plugin

I try to run the script "ghidra_wasm.py" from within Ghidra but got this error :
```

ghidra_wasm.py> Running...
Traceback (most recent call last):
  File ".......................\Il2CppDumper-v6.7.8\ghidra_wasm.py", line 9, in <module>
    WasmLoader.loadElementsToTable(currentProgram, WasmAnalysis.getState(currentProgram).module, 0, 0, 0, monitor)
	at wasm.analysis.WasmAnalysis.<init>(WasmAnalysis.java:51)
	at wasm.analysis.WasmAnalysis.getState(WasmAnalysis.java:37)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
java.lang.NullPointerException: java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getStart()" because the return value of "ghidra.program.model.mem.Memory.getBlock(String)" is null
ghidra_wasm.py> Finished!

```

Thanks!!

**Comment by nneonneo** [comment]
Hmm, I’m not sure how that can happen. Did you load a Wasm file using the plugin? The “.module” memory region that this line of code is loading should be predefined by the WasmLoader during construction (in createModuleBlock). Perhaps you didn’t load the file as a Wasm file, or the .module block was manually edited/deleted?

**Comment by seltix5** [comment]
I did not see any usage instructions thus I run it as a normal script from the Script Manager, I suppose that is not the way then?

The ghidra_wasm.py file generated by il2CppDumper starts like this :

```
# -*- coding: utf-8 -*-
import json

from wasm import WasmLoader
from wasm.analysis import WasmAnalysis
from ghidra.util.task import ConsoleTaskMonitor

monitor = ConsoleTaskMonitor()
WasmLoader.loadElementsToTable(currentProgram, WasmAnalysis.getState(currentProgram).module, 0, 0, 0, monitor)

runScript("analyze_dyncalls.py")
.....
```
I did not edited it.

**Comment by nneonneo** [comment]
That should work, but how did you load the .wasm program in the first place? That is, what program are you using this script on?

**Comment by seltix5** [comment]
Oh, I think I had the wrong idea of what wasm is. In ghidra I have a il2cpp file loaded, I suppose this script is only for a different specific type of binary?
Sorry :s

**Comment by nneonneo** [comment]
This plugin and script is meant for WebAssembly (Wasm) programs. Il2Cpp can produce Wasm programs, but it can also produce Linux, Windows, macOS, iOS, ... binaries for a variety of architectures (ARM, x86, ...).

**Comment by seltix5** [comment]
thanks for the explanation and sorry for my noob post =)
