### ISSUE TITLE
Apache License 2.0

### ISSUE THREAD

**Issue by nneonneo** [nneonneo/ghidra-wasm-plugin#12]
I’ve posted a PR to the upstream Ghidra repository to try and get WebAssembly support into core Ghidra. As part of this, the code will need to be licensed as Apache License 2.0. 

The following contributors provided code that appears in this repository: @xWTF, @namazso, @andr3colonel, @garrettgu10, @cmorin6. I will need your sign off to license your contributions as Apache License 2.0 so they can be merged upstream.

Please give a quick reply to this issue saying whether or not you permit licensing your contributions to this repository as Apache License 2.0.

**Comment by namazso** [comment]
Relicensing my contributions to Apache2 is fine by me

**Comment by xWTF** [comment]
LGTM

**Comment by garrettgu10** [comment]
Yes!! 😻

**Comment by andr3colonel** [comment]
Sure

**Comment by cmorin6** [comment]
Yes no problem!

**Comment by nneonneo** [comment]
Thanks everyone for your quick responses! Closing as resolved. Let's hope the work will be accepted upstream soon :)
