### ISSUE TITLE
Question: Is it possible to emulate __wasm_call_ctors?

### ISSUE THREAD

**Issue by hazyone** [nneonneo/ghidra-wasm-plugin#16]
Hi!
I have wasm binary, that have lot of runtime indirect_calls, but I need to run this binary to analyze(in memory) what function will be called.
Pointers to this indirect functions in memory created via `__wasm_call_ctors`, but it's impossible to analyze this function in manual mode.

**Comment by nneonneo** [comment]
Emulation is possible; see [`emulate_writev.py`](https://github.com/nneonneo/ghidra-wasm-plugin/blob/master/ghidra_scripts/emulate_writev.py) for an example of how to use the emulator. That script runs `main` with `writev` hooked to obtain the program's output.

Not everything is supported, though. If there's something that isn't supported, please provide some more detail on what isn't working (e.g. a sample file).

**Comment by nneonneo** [comment]
Closing as stale.
