### ISSUE TITLE
FAILURE: Build failed with an exception using Ghidra 11.1

### ISSUE THREAD

**Issue by VINSERTF128** [nneonneo/ghidra-wasm-plugin#21]
Importing the plug-in in Ghidra 11.1 give me an error about the package ghidra.app.util.bin.format.dwarf.next.sectionprovider.
When building give me this error:
```java
/Users/user/Downloads/ghidra-wasm-plugin-master/src/main/java/wasm/analysis/WasmDWARFAnalyzer.java:19: error: package ghidra.app.util.bin.format.dwarf.next.sectionprovider does not exist
import ghidra.app.util.bin.format.dwarf.next.sectionprovider.DWARFSectionProviderFactory;
                                                            ^
/Users/tanuki/Downloads/ghidra-wasm-plugin-master/src/main/java/wasm/analysis/WasmDWARFAnalyzer.java:31: error: cannot find symbol
                                && DWARFSectionProviderFactory.createSectionProviderFor(program, TaskMonitor.DUMMY) != null) {
                                   ^
  symbol:   variable DWARFSectionProviderFactory
  location: class WasmDWARFAnalyzer
2 errors
```
I temporarily delete WasmDWARFAnalyzer.java while building so I can import the plug-in without issue.
Maybe in Ghidra 11.1 some function for analyzing DWARF stuffs are moved in other packages, infact in this new update they add support for DWARF5 and other improvements.

**Comment by nneonneo** [comment]
With the implementation of DWARF5, the DWARF handling code has moved from `ghidra.app.util.bin.format.dwarf4.next` to `ghidra.app.util.bin.format.dwarf`. Making that renaming fixes the build issue and appears to allow the plugin to load DWARF metadata just fine. 

I’ll be fixing this shortly and spinning a new release specifically for 11.1. Thanks for the report!
